n cycle_values af loudnorm=I=-30 loudnorm=I=-15 anull
Ctrl+DEL run "trash" "${path}"; show-text "Moved to trash: ${path}"
# bookmarker-menu.lua
B script_message bookmarker-menu
b script_message bookmarker-quick-save
ctrl+b script_message bookmarker-quick-load
