#save-watch-history

volume=75

# subs
sub-font="Fira Code"
sub-bold=yes
sub-auto="fuzzy"

# Hardware acceleration
# profile=high-quality
# vo=gpu-next
hwdec=auto

# Window
force-window=yes
fullscreen=yes
border=no
title-bar=no

# Screenshot: s
screenshot-template="%F - [%P] (%#01n)"

# .
audio-device=pipewire
save-position-on-quit=no

# Keep the video's aspect ratio (no stretching)
keepaspect=yes
# Allow the window to be any size (fills the i3 tile)
keepaspect-window=no

# video-sync=display-resample makes it so that if audio and video go out of sync, then instead of dropping video frames, it will resample the audio.
video-sync=display-resample

# ytdl
# ytdl-format="((bestvideo[width<=?1920]/bestvideo)+(bestaudio[acodec=opus]/bestaudio[acodec=vorbis]/bestaudio[acodec=aac]/bestaudio)/best"
ytdl-format="bestvideo[height<=?1080]+bestaudio/best"
cache=yes
demuxer-max-bytes=150MiB
demuxer-max-back-bytes=50MiB
network-timeout=100
stream-buffer-size=2MiB



# Fix jerky playback/tearing for xorg
# vo=xv

alang=eng
