# Recommended location for database
db_file                   "~/.config/mpd/database"
playlist_directory        "~/.config/mpd/playlists"

music_directory           "~/media/music"

follow_outside_symlinks   "yes"
follow_inside_symlinks    "yes"

zeroconf_enabled          "no"
auto_update               "yes"

replaygain                  "track"
replaygain_preamp           "0"
replaygain_missing_preamp   "-6"

audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
}
